/*
 * This code was generated by ojc.
 */
public class ObjectExample
{

    public void objectMethod( FooData data )
    {
        trace.add( new java.lang.Integer( 1 ) );
        int a = data.getA();
        int b = 0;
        if (a < 1) {
            trace.add( new java.lang.Integer( 2 ) );
            b++;
        } else {
            trace.add( new java.lang.Integer( 3 ) );
            if (a > 3) {
                trace.add( new java.lang.Integer( 4 ) );
                b--;
            } else {
                trace.add( new java.lang.Integer( 5 ) );
                if (a > 7 && a < 10) {
                    trace.add( new java.lang.Integer( 6 ) );
                    b = b + 10;
                } else {
                    trace.add( new java.lang.Integer( 7 ) );
                    b = b + 11;
                }
            }
        }
    }

    
    static java.util.Set trace = new java.util.HashSet();

    
    public static void newTrace()
    {
        trace = new java.util.HashSet();
    }

    
    public static java.util.Set getTrace()
    {
        return trace;
    }

}
