/*
 * This code was generated by ojc.
 */
import java.util.*;


public class Triangle
{

    public Triangle()
    {
        super();
        trace.add( new Integer( 1 ) );
    }

    public static String checkTriangle( int side1, int side2, int side3 )
    {
        trace.add( new Integer( 2 ) );
        String type = "";
        if (side1 + side2 > side3 && side3 + side2 > side1 && side1 + side3 > side2) {
            trace.add( new Integer( 3 ) );
            if (side1 != side2 && side1 != side3 && side2 != side3) {
                trace.add( new Integer( 4 ) );
                type = "Is triangle scalene";
            } else {
                trace.add( new Integer( 5 ) );
                if (side1 == side2 && side1 != side3 || side1 == side3 && side1 != side2 || side2 == side3 && side2 != side1) {
                    trace.add( new Integer( 6 ) );
                    type = "Is triangle isosceles ";
                } else {
                    trace.add( new Integer( 7 ) );
                    type = "Is triangle equilateral ";
                }
            }
        } else {
            trace.add( new Integer( 8 ) );
            type = "Not a triangle";
        }
        return type;
    }

    
    static Set trace = new HashSet();

    
    public static void newTrace()
    {
        trace = new HashSet();
    }

    
    public static Set getTrace()
    {
        return trace;
    }

}
